name = input("Indicate your name: ")
department = input("Enter your AWS Cloud Club department: ")
galaxy = input("Specify the galaxy to which you belong: ")
print("")
print("Your Department's DP Blast Caption:")
print("")
print("🚀Deploying...I'm " + name + " representing the " + department + ". I'm thrilled to commence our expedition into the vast and uncharted realm of the " + galaxy + ". Together, we'll navigate this exciting frontier of technology! 🌌🌟💻")